title = 'example_map'

[sim]
    time_out=10000
    skip=true
    seed=10001

[robot]
    fuel=3000
    energy_consumption=10
    move_consumption=10
    position_x=8
    position_y=8
    vision_sight=1

[map]
    name='example_map'
    width=17
    height=17
    max_energy=20
    num_obstacle=38
    debug=true
    [map.fix]
        enable=true
        pos_x=[0,1,2,1,2,3, 5,6,7,8,9,10,5,6,7,8,9,10, 12,16,12,16, 5,5,6,6,5,5,6,6,15,15,16,16,15,15,16,16]
        pos_y=[8,7,6,11,10,9, 3,3,3,3,3,3,4,4,4,4,4,4, 1,1,6,6, 9,10,9,10,15,16,15,16,9,10,9,10,15,16,15,16]
    [map.charger]
        enable=true
        chance=4
        pos_x=[8]
        pos_y=[8]

