title = 'example_map'

[sim]
    time_out=10000
    skip=true
    seed=10001

[robot]
    fuel=3000
    energy_consumption=10
    move_consumption=10
    position_x=8
    position_y=8
    vision_sight=1

[map]
    name='example_map'
    width=17
    height=17
    max_energy=20
    num_obstacle=38
    debug=true
    [map.fix]
        enable=true
        pos_x=[0,1,2,3,4,5,0,1,2,3,4,5, 0,0,4,4, 11,12,13,14,15,16, 9,10,9,10,9,10,9,10,15,16,15,16,15,16,15,16]
        pos_y=[0,0,0,0,0,0,1,1,1,1,1,1, 3,8,3,8, 1,2,3,0,1,2, 5,5,6,6,15,15,16,16,5,5,6,6,15,15,16,16]
    [map.charger]
        enable=true
        chance=4
        pos_x=[8]
        pos_y=[8]

